import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import ThemeRegistry from '@/components/ThemeRegistry';
import "./globals.css";

// const geistSans = LocalFont({
//   src: 'public/fonts/Geist-Regular.woff2',
//   variable: "--font-geist-sans",
// });

// const geistMono = LocalFont({
//   src: 'public/fonts/GeistMono-Regular.woff2',
//   variable: "--font-geist-mono",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
