// 基本的にページ共通のレイアウトを定義
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import Header from '@/components/Header';
import SideMenu from '@/components/SideMenu';
import ThemeRegistry from '@/components/ThemeRegistry';
import { auth0 } from "@/lib/auth0";
import "./globals.css";

// const geistSans = LocalFont({
//   src: 'public/fonts/Geist-Regular.woff2',
//   variable: "--font-geist-sans",
// });

// const geistMono = LocalFont({
//   src: 'public/fonts/GeistMono-Regular.woff2',
//   variable: "--font-geist-mono",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // request /auth/profile to fetch the user session
  const session = await auth0.getSession();

  // If no session, show sign-up and login buttons
  // TODO: デザインを考える
  if (!session) {
    return (
      <html lang="en">
        <body className={``}>
          <ThemeRegistry>
            <div style={{ display: 'flex' }}>
              <main>
                <a href="/auth/login?screen_hint=signup">
                  <button>Sign up</button>
                </a>
                <a href="/auth/login">
                  <button>Log in</button>
                </a>
              </main>
            </div>
          </ThemeRegistry>
        </body>
      </html>
    );
  }
  return (
    <html lang="en">
      <body className={``}>
        <ThemeRegistry>
          <div style={{ display: 'flex' }}>
            <SideMenu />
            <Header />
            <main style={{ flex: 1, overflowY: 'auto', marginTop: '64px' }}>
              {children}
            </main>
          </div>
        </ThemeRegistry>
      </body>
    </html>
  );
}
